Console.WriteLine("## Exercício Classes e Métodos 7 ##\n");

Carro chevrolet = new Carro("Sedan", "Chevrolet", "Onix", 2016, 110);
Carro ford = new Carro("SUV", "Ford", "Ecosport", 2018, 120);

Console.WriteLine("\n-----------\tCHEVROLET\t-----------");
Console.WriteLine("\nParte 1");
Console.WriteLine($"\nModelo: {chevrolet.Modelo}");
Console.WriteLine($"Montadora: {chevrolet.Montadora}");
Console.WriteLine($"Marca: {chevrolet.Marca}");
Console.WriteLine($"Ano: {chevrolet.Ano}");
Console.WriteLine($"Potência: {chevrolet.Potencia}cv");
chevrolet.Acelerar(chevrolet.Marca);
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 2");
double chevroleteVelocidadeMaxima = chevrolet.VelocidadeMaxima(chevrolet.Potencia);
Console.WriteLine($"\nA velocidade máxima é de {chevroleteVelocidadeMaxima}Km/h");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 3");
int chevroletPotencia = chevrolet.Potencia;
Console.WriteLine($"\nCom o aumento de potência TEMPORÁRIO (por VALOR +3cv) ela irá para {chevrolet.AumentarPotencia(chevroletPotencia)}cv");
Console.WriteLine($"Potência atual: {chevroletPotencia}cv");
Console.WriteLine($"Com o aumento de potência DEFINITIVO (por REFERÊNCIA +5cv) ela irá para {chevrolet.AumentarPotencia(ref chevroletPotencia)}cv");
Console.WriteLine($"Potência atual: {chevroletPotencia}cv");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 4");
int chevroletAumentoPotenciaVelocidade = chevrolet.AumentarPotenciaVelocidade(chevroletPotencia, out double velocidadeChevrolet);
Console.WriteLine($"\nAumento de Potência TEMPORÁRIO (por VALOR +7): {chevroletAumentoPotenciaVelocidade}cv");
Console.WriteLine($"Velocidade com aumento temporário de potência (OUT): {velocidadeChevrolet}cv");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 5");
Console.WriteLine("\nChamada sem definição do Ano");
chevrolet.ExibirInfo(potencia: chevrolet.Potencia, montadora: chevrolet.Montadora, marca: chevrolet.Marca, modelo: chevrolet.Modelo);
Console.WriteLine("\nChamada com definição do Ano");
chevrolet.ExibirInfo(potencia: chevrolet.Potencia, montadora: chevrolet.Montadora, marca: chevrolet.Marca, modelo: chevrolet.Modelo, ano: chevrolet.Ano);
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 6");
Carro.ObterValorIPVA();
Console.WriteLine($"Valor do IPVA: {Carro.ValorIpva}");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 7");
Console.WriteLine($"Mudança de ano de {chevrolet.Ano} para 1999");
chevrolet.Ano = 1999;
Console.WriteLine("Validação na propriedade Ano: Menor que 2000 = 2000. Maior que 2022 = 2022");
Console.WriteLine($"Ano: {chevrolet.Ano}");
Console.WriteLine($"Retorno de ano de {chevrolet.Ano} para 2018");
chevrolet.Ano = 2016;
Console.WriteLine("Validação na propriedade Ano: Menor que 2000 = 2000. Maior que 2022 = 2022");
Console.WriteLine($"Ano: {chevrolet.Ano}");

Console.WriteLine();
Console.WriteLine("\n-----------\tFORD\t-----------");
Console.WriteLine("\nParte 1");
Console.WriteLine($"\nModelo: {ford.Modelo}");
Console.WriteLine($"Montadora: {ford.Montadora}");
Console.WriteLine($"Marca: {ford.Marca}");
Console.WriteLine($"Ano: {ford.Ano}");
Console.WriteLine($"Potência: {ford.Potencia}cv");
ford.Acelerar(ford.Marca);
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 2");
double fordVelocidadeMaxima = ford.VelocidadeMaxima(ford.Potencia);
Console.WriteLine($"\nA velocidade máxima é de {fordVelocidadeMaxima}Km/h");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 3");
int fordPotencia = ford.Potencia;
Console.WriteLine($"\nAumento de potência TEMPORÁRIO (por VALOR) ela irá para {ford.AumentarPotencia(fordPotencia)}cv");
Console.WriteLine($"Potência atual: {fordPotencia}cv");
Console.WriteLine($"Aumento de potência DEFINITIVO (por REFERÊNCIA) ela irá para {ford.AumentarPotencia(ref fordPotencia)}cv");
Console.WriteLine($"Potência atual: {fordPotencia}cv");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 4");
int fordAumentoPotenciaVelocidade = ford.AumentarPotenciaVelocidade(fordPotencia, out double velocidadeFord);
Console.WriteLine($"\nAumento de Potência TEMPORÁRIO (por VALOR +7): {fordAumentoPotenciaVelocidade}cv");
Console.WriteLine($"Velocidade com aumento temporário de potência (OUT): {velocidadeFord}cv");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 5");
Console.WriteLine("\nChamada sem definição do Ano");
ford.ExibirInfo(potencia: ford.Potencia, montadora: ford.Montadora, marca: ford.Marca, modelo: ford.Modelo);
Console.WriteLine("\nChamada com definição do Ano");
ford.ExibirInfo(potencia: ford.Potencia, montadora: ford.Montadora, marca: ford.Marca, modelo: ford.Modelo, ano: ford.Ano);
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 6");
Carro.ObterValorIPVA();
Console.WriteLine($"Valor do IPVA: {Carro.ValorIpva}");
Console.WriteLine("\n-------------------------------");
Console.WriteLine("\nParte 7");
Console.WriteLine($"Mudança de ano de {ford.Ano} para 2023");
ford.Ano = 2023;
Console.WriteLine("Validação na propriedade Ano: Menor que 2000 = 2000. Maior que 2022 = 2022");
Console.WriteLine($"Ano: {ford.Ano}");
Console.WriteLine($"Retorno de ano de {ford.Ano} para 2018");
ford.Ano = 2018;
Console.WriteLine("Validação na propriedade Ano: Menor que 2000 = 2000. Maior que 2022 = 2022");
Console.WriteLine($"Ano: {ford.Ano}");


Console.ReadKey();
